function Data = load_notc_data(fn)

s = load(fn);
Data = s.data_session;

Data.Properties.VariableNames = {
   'ChairVelocityFeedback', ...
   'HomePosition', ...
   'ChairPositionFeedback', ...
   'ButtonLeft', ...
   'ButtonRight', ...
   'StartTriggerRead', ...
   'ChairVelocityCommandCopy', ...
   'SyncPulse'};
