function average_left_right(folder, transducer)

left = cfts.calib.read(fullfile(folder, [transducer '.Left.calib']));
right = cfts.calib.read(fullfile(folder, [transducer '.Right.calib']));

mag = 0.5*(left.Mag + right.Mag);
phase = 0.5*(left.Phase + right.Phase);

cfts.calib.resave(...
   fullfile(folder, [transducer '.Left.calib']), ...
   left.Freq, ...
   mag, ...
   phase, ...
   fullfile(folder, [transducer '.Average.calib']));